### ISSUE TITLE
Search isn't visible from profile pages

### ISSUE THREAD

**Issue by kalenjordan** [kalenjordan/pros.global#61]

**Comment by filrak** [comment]
Wanted to help with this but it looks like it happens just in certain browser env or you already fixed it ;) Can you give me a steps to repro?
![image](https://user-images.githubusercontent.com/15185752/51910248-f8728280-23ce-11e9-8108-ebbb5c9aee96.png)
![image](https://user-images.githubusercontent.com/15185752/51910260-fe686380-23ce-11e9-9fc1-1b1d799a5094.png)

**Comment by kalenjordan** [comment]
Oh thanks! I actually already fixed it.
